return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  lazy = false,
  cmd = { 'TSInstall', 'TSUninstall', 'TSUpdate', 'TSUpdateSync', 'TSInstallInfo', 'TSInstallSync' },
  -- [[ Configure Treesitter ]] See `:help nvim-treesitter`
  opts = {
    ensure_installed = {
      'lua',
      'python',
      'vimdoc',
      'vim',
      'regex',
      'terraform',
      'sql',
      'dockerfile',
      'toml',
      'json',
      'gitignore',
      'yaml',
      'make',
      'cmake',
      'ninja',
      'markdown',
      'markdown_inline',
      'rst',
      'bash',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = { enable = true, disable = { 'ruby' } },
  },
}